### ISSUE TITLE
2 questions on multiple HC-SR04 diagram

### ISSUE THREAD

**Issue by cdnhermit** [gamgine/Arduino-lib-HCSR04#4]
Hello, thank you for your contribution. I am looking at connecting many Ultrasonic sensor with my car, as I am new to this Arduino stuff I am not certain of what I am doing.  
Your diagram (image) 1) connects the power to the ground, is this an error? and 2) there is about in the middle of the image a yellow (trig) small cable to connect both sides of the breadboard and I do not understand it's purpose. I would appreciate if you could look into those 2 questions. Thank you

**Comment by gamegine** [comment]
Hello
the power on ground is a mistake.
thank you for reporting this error, i did not see it.
the yellow cable in the middle is connected to nothing
I took the opportunity to remove it on the new image
