### ISSUE TITLE
Incorrect formula used for distance calculation?

### ISSUE THREAD

**Issue by jcdevel** [gamgine/Arduino-lib-HCSR04#5]
Hi there,

Thank you very much for this software. I was looking at the code and the distance is calculated as the echo pulse width divided by 58.0. However, according to the HC-SR04 available in Sparkfun, the division by 58.0 applies to the delay between the trigger and the echo, but when using the echo pulse width, the right formula should be (d * 340.0(m/s) / 2.0). Could you verify this?

Thanks in advance.

**Comment by gamegine** [comment]
hello, 
the value **58.8235** represents a simplified version of the formula **(d * 340.0 (m / s) / 2.0)**.
```
(340/10000)) / 2.0 = 0.017
1 / 58.8235 = 0.017 
```

**Comment by jcdevel** [comment]
Thank you for the response. The HC-SR04 user manual was not very clear about this and led to think there are other ways to calculate the distance:

> You can calculate the range through the time interval between sending trigger signal and receiving echo signal

If I understood correctly, this sentence is not true, since the distance is proportional to the echo pulse width, and not the delay between trigger and echo. It is more clear now.
